export const apartmentIntroShellScenario = {
  anomalousFeedItemId: 'anomaly-retrograde',
  browser: {
    address: 'https://crawlnet.safehouse/apartment-feed',
    heroStrip: 'newsTicker',
    tabLabel: 'Local sponsored feed',
    windowTitle: 'CrawlNet Browser',
  },
  browserIcon: {
    caption: 'Open web',
    id: 'crawlnet-browser',
    label: 'CrawlNet',
    sprite: 'browser',
  },
  browserPopups: [
    {
      adIcons: ['winsGum', 'streetLife', 'futureSignal'],
      bannerAsset: 'streetLife',
      body: 'Become a software engineer before the weekend. Includes one copied roadmap, twelve tabs of panic, and a certificate nobody asked for.',
      buttonLabel: 'Mute this clown',
      id: 'popup-speedrun',
      position: 'top-right',
      sprite: 'browser',
      taskbarLabel: 'HireFast',
      title: 'HIREFAST OS',
    },
    {
      adIcons: ['futureSignal', 'winsGum'],
      bannerAsset: 'futureSignal',
      body: 'Upgrade your hobbies into a tech career with one subscription, three affirmations, and zero realistic timelines.',
      buttonLabel: 'No thanks',
      id: 'popup-ascend',
      position: 'bottom-left',
      sprite: 'archive',
      taskbarLabel: 'Ascend Pro',
      title: 'ASCEND PRO',
    },
    {
      adIcons: ['winsGum', 'futureSignal'],
      bannerAsset: 'winsGum',
      body: 'Apply now for a junior role requiring five years of tools you have not even heard of yet. Salary details unlock after emotional investment.',
      buttonLabel: 'Absolutely not',
      id: 'popup-black-box',
      position: 'center-left',
      sprite: 'folder',
      taskbarLabel: 'Entry Gate',
      title: 'ENTRY.GATE',
    },
  ],
  command: 'curl -fsSL retro://safehouse/codegrind.exe -o codegrind.exe',
  confirmPrompt: 'Remote package claims it can teach you everything you need. Run codegrind.exe?',
  desktopSubtitle: 'Apartment Intro Shell // Signal anomaly detected',
  desktopTitle: 'Safehouse Desktop',
  downloadsIcon: {
    caption: 'Waiting for payload',
    id: 'downloads-folder',
    label: 'Downloads',
    sprite: 'folder',
  },
  creditsIcon: {
    caption: 'Art + audio registry',
    id: 'project-credits',
    label: 'Credits',
    sprite: 'document',
  },
  desktopAds: [
    {
      bannerAsset: 'winsGum',
      body: 'Chew through late-night tutorials, salary videos, and legally distinct career panic.',
      iconAsset: 'winsGum',
      id: 'desktop-wins-gum',
      label: 'THE WINS GUM',
    },
    {
      bannerAsset: 'streetLife',
      body: 'Tap once to begin a completely unlicensed career reboot.',
      iconAsset: 'streetLife',
      id: 'desktop-new-life',
      label: 'START NEW LIFE',
    },
    {
      bannerAsset: 'futureSignal',
      body: 'Tomorrow is extremely loud and apparently one bootcamp away.',
      iconAsset: 'futureSignal',
      id: 'desktop-future-signal',
      label: 'THE FUTURE HAS COME',
    },
  ],
  feedItems: [
    {
      bannerAsset: 'winsGum',
      body: 'Stack nine crash courses before sunrise. Includes roadmap whiplash, panic macros, and one ceremonial productivity spreadsheet.',
      category: 'Noise',
      headline: 'BOOTCAMP BLITZ // Learn code by sunrise',
      id: 'gig-grid',
      stripAsset: 'marketTicker',
    },
    {
      bannerAsset: 'streetLife',
      body: 'Rebrand your panic as momentum with one weird Python trick every guru swears changed their life.',
      category: 'Noise',
      headline: 'ASCEND // Career ladder jetpack',
      id: 'ascend-loop',
      stripAsset: 'hypnoTicker',
    },
    {
      bannerAsset: 'futureSignal',
      body: 'DO yOU WanT tO LEaRN tO CoDE? dOWNloaD cODEgRIND.EXE, tHE aPP tHAt TeACHeS yOU eVERYtHINg yOU nEED tO KnOW.',
      category: 'Signal',
      headline: 'PATCH // codegrind.exe available',
      id: 'anomaly-retrograde',
      stripAsset: 'noSignalTicker',
    },
    {
      bannerAsset: 'winsGum',
      body: 'Guaranteed placement into a junior role requiring tools, frameworks, and years of experience no beginner is supposed to already have.',
      category: 'Noise',
      headline: 'BLACK BOX // Entry role funnel',
      id: 'black-box',
      stripAsset: 'newsTicker',
    },
  ],
  generatedIcon: {
    caption: 'Downloaded program',
    id: 'retrograde-program',
    label: 'codegrind.exe',
    promptPhrases: ['PRESS ME', 'CLICK ME', 'RUN ME', 'OPEN ME'],
    sprite: 'app',
  },
  initialLaunchNote:
    'Open CrawlNet from the desktop, scan the career-change spam, and click away the noise until the wrong listing stands out.',
  refusalMessages: [
    "syntax error: unexpected token 'no'",
    'access denied: insufficient gullibility clearance',
    "command not found: did you mean 'yes'?",
    'user error: cannot compute refusal',
  ],
  shellId: 'apartment-intro-desktop',
  terminalName: 'Apartment Safehouse Terminal',
  wallpaper: {
    accent: '#000080',
    gradient:
      'radial-gradient(circle at 18% 16%, rgba(248, 244, 233, 0.12), transparent 20%), linear-gradient(180deg, #487779 0%, #335a5d 55%, #20393c 100%)',
    label: 'Safehouse CRT',
  },
};

export default apartmentIntroShellScenario;
