/**
 * Tower Defense V2 - Panel Actions Props
 */

import { useMemo } from 'react';

export default function useTowerDefenseV2PanelActions({
  shouldShowVerificationControls,
  handleRunCode,
  handleRunCodeOutput,
  handleSubmitSolution,
  handleRefineSolution,
  isExecuting,
  isRefining,
  isWatchingAd,
  refinementLimitReached,
  canRefineSolution,
  initialCodeGenerated,
  codeSubmitted,
  isAnyActionInProgress,
  currentActionType,
  formattedTime,
  setShowAdModal,
  handleResetGame,
  validatedGameSettings,
  handleGameSettingsChange,
  canEditGameSettings,
  difficultyBaseStats,
  isLearningMode,
  actionCosts,
}) {
  return useMemo(
    () => ({
      shouldShowVerificationControls,
      onRunCode: handleRunCode,
      onRunOutput: handleRunCodeOutput,
      onSubmitSolution: handleSubmitSolution,
      onRefineSolution: handleRefineSolution,
      isExecuting,
      isRefining,
      isWatchingAd,
      refinementLimitReached,
      canRefineSolution,
      initialCodeGenerated,
      codeSubmitted,
      isAnyActionInProgress,
      currentActionType,
      formattedTime,
      onShowAdModal: () => setShowAdModal(true),
      onResetGame: handleResetGame,
      gameSettings: validatedGameSettings,
      onGameSettingsChange: handleGameSettingsChange,
      canEditGameSettings,
      difficultyMinimums: difficultyBaseStats,
      isLearningMode,
      actionCosts,
    }),
    [
      actionCosts,
      canEditGameSettings,
      canRefineSolution,
      codeSubmitted,
      currentActionType,
      difficultyBaseStats,
      formattedTime,
      handleGameSettingsChange,
      handleRefineSolution,
      handleResetGame,
      handleRunCode,
      handleRunCodeOutput,
      handleSubmitSolution,
      initialCodeGenerated,
      isAnyActionInProgress,
      isExecuting,
      isRefining,
      isWatchingAd,
      isLearningMode,
      refinementLimitReached,
      setShowAdModal,
      shouldShowVerificationControls,
      validatedGameSettings,
    ]
  );
}
